export const GET_TASKS = 'GET_TASKS'
export const SET_TASK = 'SET_TASK'
export const SAVE_TASK = 'SAVE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const SET_TITLE = 'SET_TITLE'
export const SET_DESCRIPTION = 'SET_DESCRIPTION'
export const SET_STATUS = 'SET_STATUS'
export const GET_ERRORS = 'GET_ERRORS'